### ISSUE TITLE
是不是还不支持热更新啊

### ISSUE THREAD

**Issue by hipi** [zlxbuzz/parcel-demo#2]
修改.vue文件没有热更新

**Comment by zlxbuzz** [comment]
@chenyeah Parcel 的 HMR 实现支持开箱即用的 JavaScript 和 CSS 资源，目前对于js css的修改可以更新，html不行

**Comment by chenyeah** [comment]
@zlxbuzz 可是我修改了你项目里的index.html 页面是刷新了的

**Comment by zlxbuzz** [comment]
@chenyeah 我指的是vue文件哈。
