### ISSUE TITLE
跑不起来

### ISSUE THREAD

**Issue by Peter-90** [zlxbuzz/parcel-demo#4]
Server running at http://localhost:1234
×  C:\Users\shiwei.peng\Desktop\Temporary Files\parcel-demo\src\app.vue:34:25: Cannot resolve dependency 'vue'
  32 |                     this.$router.push('/index')
  33 |                 }else if(select === 'detail'){
> 34 |                     this.$router.push('/detail')
     |                          ^
  35 |                 }
  36 |             }
  37 |         }
报这个错

**Comment by zlxbuzz** [comment]
@Peter-90 你是引了`vue`？这个例子的`vue.js`是通过`cdn`挂载的

**Comment by Peter-90** [comment]
嗯 我是直接把你的项目克隆下来的 怎么才能跑起来呢

**Comment by zlxbuzz** [comment]
@Peter-90 如果`import`了`vue` 建议`yarn add vue`，将`vue`放到`node_modules`里吧，把`index.html`中的`cdn`删了，`index.js`最上面`import Vue from 'vue'`

**Comment by Peter-90** [comment]
@zlxbuzz 好的 谢啦

**Comment by zlxbuzz** [comment]
@Peter-90  试了下 应该是你的`parcel`版本比较新的问题，最好还是通过`yarn.lock`来安装固定的依赖版本来运行，毕竟目前这个还不是很稳定，可能会有问题。
