### ISSUE TITLE
如何使用parcel 将 /js /css /images 输出/dist对应的 /dist/js...

### ISSUE THREAD

**Issue by lolisTop** [zlxbuzz/parcel-demo#5]
你好 问个问题 如何使用parcel 将 /js /css /images 输出/dist对应的 /dist/js /dist/css  /dist/images
这种

**Comment by zlxbuzz** [comment]
@feiyaj 这个版本支持不是很好，暂时不行

**Comment by DimaLiLongJi** [comment]
可以的 但是得写个shell 脚本麻烦一点，而且要把文件分开打包。
`NODE_ENV=development parcel watch 文件名 -d dist/对应的地方 `

**Comment by zlxbuzz** [comment]
@DimaLiLongJi 自己处理肯定可以，但是我觉得反而把问题复杂化了，变成另一个webpack了

**Comment by lolisTop** [comment]
@zlxbuzz @DimaLiLongJi 谢谢 ~~我大概知道什么情况了 刚刚去知乎搜了下打包的概念，即是整合所有写代码..提高了加载速度这种..初次使用确实不能按照传统页面想法去搞，受教了。
