### ISSUE TITLE
.babelrc 书写问题

### ISSUE THREAD

**Issue by YunYouJun** [zlxbuzz/parcel-demo#7]
```
{
  "presets": [
    ["env"]
  ]
}
```
您好，项目中 `.babelrc` 文件 `presets` 书写如上，但是我运行时会发生如下报错。

> Server running at http://localhost:1234
×  C:\Users\YunYou\Documents\GitHub\xxx\src\index.js: Cannot read property 'targets' of undefined
    at loadBabelrc (C:\Users\YunYou\Documents\GitHub\xxx\node_modules\parcel-bundler\src\utils\getTargetEngines.js:113:23)
    at \<anonymous\>

---

参见 [babel 中文网](https://babeljs.cn/) 后，书写形式如下。

```
{
  "presets": ["env"]
}
```

修改后，报错成功解决。

**Comment by zlxbuzz** [comment]
@YunYouJun 看了下代码，你用的应该是最新的`parcel-bundler`, https://github.com/parcel-bundler/parcel/blob/master/src/utils/getTargetEngines.js#L113这里有个对`env`的判断，如果是二维数组，则默认是需要有babel的`options`,我忽略的参数,所以报错了吗，两种写法都是可以的。我这个demo还是针对1.2.0的`parcel`,所以推荐用`yarn`来安装依赖，可以等更加稳定后去完善这个例子。

**Comment by YunYouJun** [comment]
嗯，谢谢。
